import type { NextPage } from 'next';
import Head from 'next/head';
import { MouseEvent, useState } from 'react';
import Conclusion from './api/spanish/conclusion';
import ConclusionComponent from '../components/ConclusionComponent';
import SelectWrittingComponent from '../components/SelectWrittingComponent';

const Home: NextPage = () => {
  const [selectedComponent, setSelectedComponent] = useState('index');
  const onSubmit = () => {};
  const onSelectChange = (event: any) => {
    setSelectedComponent(event.target.value);
  };
  return (
    <div className='h-screen m-10'>
      <Head>
        <title>Essay it!</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className='w-full h-full flex flex-col items-center'>
        <h1 className='text-6xl mb-5'>GPT3</h1>
        <div className='flex w-full h-full'>
          <div className='flex flex-col flex-start border-r-stone-90 flex-1 border-r-black border-r'>
            {/* <ConclusionComponent /> */}
            {
              {
                index: (
                  <SelectWrittingComponent onSelectChange={onSelectChange} />
                ),
                'Conclusión practica': (
                  <ConclusionComponent
                    onBackClick={() => setSelectedComponent('index')}
                  />
                ),
                bar: <div> </div>,
              }[selectedComponent]
            }
          </div>

          <div className='flex flex-col flex-1'>
            <textarea
              name='text'
              className=' h-full focus:outline-none'
              value={'a'}
              onChange={(e) => console.log('')}
            ></textarea>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
