import type { NextPage } from 'next';
import Head from 'next/head';
import { MouseEvent, useState } from 'react';
import Conclusion from './api/spanish/conclusion';
import ConclusionComponent from '../components/ConclusionComponent';

const Home: NextPage = () => {
  const [animalInput, setAnimalInput] = useState('');
  const [result, setResult] = useState();
  async function onSubmit(event: any) {
    event.preventDefault();
    const response = await fetch('/api/prompt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ animal: animalInput }),
    });
    const data = await response.json();
    setResult(data.result);
    setAnimalInput('');
  }
  return (
    <div className='h-screen m-10'>
      <Head>
        <title>Essay it!</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className='w-full h-full flex flex-col items-center'>
        <h1 className='text-6xl mb-5'>GPT3</h1>
        <div className='flex w-full h-full'>
          <div className='flex flex-col flex-start border-r-stone-90 flex-1 border-r-black border-r'>
            <ConclusionComponent />
          </div>

          <div className='flex flex-col flex-1'>
            <textarea
              name='text'
              className=' h-full focus:outline-none'
              value={animalInput}
              onChange={(e) => setAnimalInput(e.target.value)}
            ></textarea>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
